# Generated by Django 5.0.7 on 2024-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(
                default="img.jpg", upload_to="image/%Y", verbose_name="Image"
            ),
            preserve_default=False,
        ),
    ]
